### ISSUE TITLE
feature request: How to control playback speed

### ISSUE THREAD

**Issue by imliubo** [chmorgan/esp32-audio-player#12]
This is a very newbie-friendly and easy-to-use library (compared to adf). However, there is currently no control interface for playback speed. Is this possible to be implemented in the future? Or if I want to implement this function, where should I start from? 

Related:
[sonic docs](https://docs.espressif.com/projects/esp-adf/en/latest/api-reference/audio-processing/audio_sonic.html)
[sonic code](https://github.com/espressif/esp-adf-libs/blob/619b3bac9a34617f288c6e68f3c587618b1c68bb/esp_codec/audio_sonic.c)
[sonic demo](https://github.com/espressif/esp-adf/tree/3c06f0a/examples/audio_processing/pipeline_sonic)

**Comment by chmorgan** [comment]
Hi @imliubo.

I'm glad to see you are having an easy time of using it. This is an interesting idea. I think you could use the write function, pass that data to the sonic library for resampling, and then only when the data from sonic is accepted into the i2s buffer you'd return from the write function and the audio player would continue decoding.

So you'd need a little bit of intermediate code to manage the flow of data.

**Comment by imliubo** [comment]
Hi @chmorgan 

Thanks for reply.
You are right! I need time to figure out how to make it work.

Have a nice day.

**Comment by chmorgan** [comment]
Open to this support via a PR.
