### ISSUE TITLE
Audio player mute and reconfig functions for MAX98357A

### ISSUE THREAD

**Issue by kungfupizza** [chmorgan/esp32-audio-player#14]
Hi,
I have been able to use this library very well, thank you! I am still have some audio issues around writing the mute and reconfig_clk functions for MAX98357A. Do you know of examples of this library being used with the above IC?

Side note: Volume control software not available with me for MAX98357A

**Comment by chmorgan** [comment]
I’m not aware of anyone using this codec at the moment.

What kinds of issues are you seeing?

If it was of interest I’d be willing to discuss a paid engagement to add support for this codec to the library. I did so for a TI codec this past year.

**Comment by kungfupizza** [comment]
My uni wouldn't fund that but if you can provide a flowchart of what these functions could do, I can build it up.

**Comment by chmorgan** [comment]
I can certainly answer specific questions if you have any.

**Comment by chmorgan** [comment]
Closing, please submit a PR if you end up adding support for this codec.
